test2.html
<br>
cheri에 바로 push가 아닌, cheri-test같이 임의의 브랜치를 생성해서 cheri에 넣어주어야합니다 :-)
<br>
=> [add]test2

sohee/IFL/[1-2]_삼각형_판별하기.html
```js
function solution(a, b, c){
let sum = a + b + c;
let max = Math.max(a, b, c);
let total = sum - max;
if(total > max){
return "Y"
} else {
return "N"
}
}
console.log(solution(6, 7, 11));
```
<br>
📐 삼각형이 만들어지는 원리
선이 짧은 길이의 합이 선이 가장 긴 길이보다 커야 삼각형이 만들어진다.
1. 가장 긴 선의 길이를 구한다.
2. 세 길이를 모두 더하고 max 의 값을 뺀다.
3. 모두 더한 총합의 값과 max 의 값을 비교해서 총합이 크다면 Y, 작다면 N
<br>
<br>
`Math.max()` 함수는 입력값으로 받은 숫자 중 가장 큰 숫자를 반환한다.
아무 요소도 주어지지 않았다면 `-Infinity`  반환
한 개 이상의 요소가 숫자로 변환되지 않는다면 `NaN`  반환
`Math.max(값1, 값2 ...)`
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Math/max
=> [1-2] 삼각형 판별하기

branch/IFR/[1-3]_연필개수.html
```
function solution(n){
return Math.ceil(n/12) ;
}
console.log(solution(178));
```
<br>
(문제 해결 과정)
<br>
<br>
처음에는 Math.floor() 을 사용하였지만,
문제를 다시 읽고, 잘못됨을 깨달아서 바로 Math.ceil()로 바꿔주었다.
Math.ceil()은 소숫점자릿수를 올려주는 메서드이다.
(사진 첨부)
<br>
<br>
(메모 및 Tip)
=> [1-3] 연필개수

branch/IFR/[1-7]_10부제.html
```
function solution(day, arr){
let result = []
arr.forEach(ele=>{if(ele%10===day){
result.push(ele);
}})
return result;
}
arr=[25, 23, 11, 47, 53, 17, 33];
console.log(solution(3, arr));
```
<br>
(문제 해결 과정)
<br>
<br>
arr에서 %10을 사용하여, 일의 자리 숫자를 가져온다.
그다음, day와 비교하여 결과값을 출력했다.
(사진 첨부)
<br>
<br>
(메모 및 Tip)
=> [1-7] 10부제

sohee/IFL/[1-3]_연필개수.html, sohee/IFL/[1-4]_1부터_N까지의_합.html
```js
function solution(n){
let answer = 0;
let i = 1;
while (i <= n) {
answer += i;
i++;
}
return answer;
}
console.log(solution(10));
```
<br>
풀다가 실수한 부분
1. for 문 밖에 변수를 선언해주어야 하는데 반복문 안에 선언하니
for 문 안에서만 인식하는 지역변수가 되어서 
return 시 answer 변수가 없다고 에러가 났다.
2. 입력받은 수까지 반복문이 돌아야 하므로 
i <= 입력받은 수 / 연산자 <= 를 사용해야하는데,
i < 입력받은 수를 사용하니까 입력받은 수의 -1 만큼 출력되었다.
<br>
<br>
=> [1-4] 1부터 N까지의 합

sohee/IFL/[1-3]_연필개수.html, sohee/IFL/[1-4]_1부터_N까지의_합.html, sohee/IFL/[1-5]_최솟값_구하기.html
```js
function solution(arr){
let answer = Math.min.apply(null, arr);
return answer;
}
let arr=[5, 3, 7, 11, 2, 15, 17];
```
<br>
`Math.min()` 함수를 사용하려고 보니 배열을 인자로 줄 수 없기 때문에
함수를 호출해서 this (또는 null) 값과 배열 (또는 유사 배열 객체) 값을 전달하는 `apply()` 함수를 알게되었다.
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Function/apply
`func.apply(thisArg, [argsArray])`
첫 번째 인자로 함수 호출에 제공 될 this의 값을 넣고(없다면 null),
두 번째 인자로 배열 또는 유사배열 객체를 넣는다.
<br>
<br>
첫 번째 인자로 null 을 넣어주는 이유를 조금 더 찾아봐야 할 것 같다.
=> [1-5] 최솟값 구하기

branch/IFR/[1-8]_일곱난쟁이.html
```
function solution(arr){
let answer=arr;
let sum=answer.reduce((a, b)=>a+b, 0);
for(let i=0; i<8; i++){
for(let j=i+1; j<9; j++){
if((sum-(answer[i]+answer[j]))===100){
answer.splice(j, 1);
answer.splice(i, 1);
}
}
}
let answerSum=0;
answer.forEach(ele=>answerSum+=ele)
if(answerSum===100){
return answer;
}else{
return "결과없음"
}
}
let arr=[20, 7, 23, 19, 10, 15, 25, 8, 13];
```
<br>
(문제 해결 과정)
<br>
<br>
문제를 도저히 해결할 수 없어서 ^^.. 답지를 보고 배꼈습니다.
근데, 인자를 절대 합쳐서 100이 나오지 않는 숫자들로 넣으니,
arr가 그대로 반환되는 것을 볼 수 있었습니다. 
그래서 밑에 추가로 합이 100이 되지 않을 때의 상황을 추가하였습니다.
(사진 첨부)
<br>
<br>
(메모 및 Tip)
문제지를 보면 주어지는 키는 100을 넘지 않는 자연수라고 적혀있습니다. 
답지에는 i와 j를 묶어서 결과를 출력하다보니, 
키는 자연스럽게 100이 될 수 없다는 것을 알 수 있었습니다.
=> [1-8] 일곱난쟁이

sohee/IFL/[1-11]_대문자_찾기.html
```js
function solution(str){
let cnt = 0;
const regex = /[A-Z]/;
for(i of str){
if(i.search(new RegExp(regex)) === 0){
cnt += 1;
}
}
return cnt;
}
let str = "KoreaTimeGood";
```
<br>
상수에 대문자 정규표현식`[A-Z]` 을 저장해놓고,
`RegExp` 생성자로 상수에 저장해놓은 정규표현식이 문자열에 존재하는지 판별하였다.
`search()` 메서드가 
i 의 문자열이 대문자면 0 소문자면 -1을 반환하기 때문에
0 인경우를 카운트변수에 담아 출력하였다.
<br>
<br>
<br>
<br>
`RegExp`
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/RegExp
`RegExp` 생성자는 패턴을 사용해 텍스트를 판별할 때 사용한다.
정규 표현식
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Regular_Expressions
정규 표현식은 문자열에 나타는 특정 문자 조합과 대응시키기 위해 사용되는 패턴이다.
`String.prototype.search()`
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/search
`search()` 메서드는 정규 …
=> [1-11] 대문자 찾기

sohee/IFL/[1-11]_대문자_찾기.html, sohee/IFL/[1-12]_대문자로_통일.html
```js
function solution(str){
return str.toUpperCase();
}
let str = "ItisTimeToStudy";
```
<br>
`toUpperCase()` 메서드로 문자열을 대문자로 변환하였다.
<br>
<br>
`String.prototype.toUpperCase()`
`toUpperCase()` 메서드는 문자열을 대문자로 변환해 반환한다.
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String/toUpperCase
=> [1-12] 대문자로 통일

sohee/IFL/[1-11]_대문자_찾기.html, sohee/IFL/[1-12]_대문자로_통일.html, sohee/IFL/[1-13]_대소문자_변환.html
```js
function solution(str){
const regex = /[A-Z]/;
let answer = "";
for(let i of str) {
answer += (i.search(new RegExp(regex)) === 0 ? i.replace(i, i.toLowerCase()) : i.replace(i, i.toUpperCase()));
};
return answer;
}
let str = "StuDY";
```
<br>
1. 정규 표현식 대문자를 상수안에 넣었고
2. for 문안에서 각각 문자열을 삼항 연산자로 
　0을 반환하면 대문자이므로 소문자로 변환,
　그 외(-1)을 반환하면 소문자이므로 대문자로 변환하였다.
3. 변환된 값을 answer 값에 누적하였다.
　answer 에 += 대신 = 을 했더니 한 문자열만 출력되서 왜 그러지? 했는데 누적 연산자(+=) 를 쓰지 않아서..
<br>
<br>
=> [1-13] 대소문자 변환

sohee/IFL/[1-11]_대문자_찾기.html, sohee/IFL/[1-12]_대문자로_통일.html, sohee/IFL/[1-13]_대소문자_변환.html, sohee/IFL/[1-14]_가장_긴_문자열.html
```js
function solution(arr){
let max = 0, answer = "";
for(i of arr){
if(max < i.length){
max = i.length;
answer = i;
}
}
return answer;
}
let arr = [5, "teacher", "time", "student", "beautiful", "good"];
```
<br>
가장 긴 문자열이라고 해서 `length` 를 사용하면 될 것 같았다.
max 변수에 배열의 `length` 가 가지는 가장 큰 값을 비교하여 계속 치환하고,
배열의 가장 큰 값을 출력해야 하니까 i 를 answer 변수에 담아주었다.
=> [1-14] 가장 긴 문자열

sohee/IFL/[1-11]_대문자_찾기.html, sohee/IFL/[1-12]_대문자로_통일.html, sohee/IFL/[1-13]_대소문자_변환.html, sohee/IFL/[1-14]_가장_긴_문자열.html, sohee/IFL/[1-15]_가운데_문자_출력.html
```js
function solution(str){
let answer = "";
let strLng = str.length;
if(strLng % 2 ===0){
answer += str[strLng/2 -1];
answer += str[strLng/2];
}else{
answer += str[Math.floor(strLng/2)];
}
return answer;
}
let str = "study"; // u
// let str = "good" // oo
```
<br>
2로 나눈 나머지가 0이면 짝수이므로, 
가운데 위치한 2개의 문자를 출력하기 위해
`length` 를 반(2)로 나눈 값의 -1(인덱스) 값과
`length` 를 반(2)로 나눈 값을 answer 변수에 넣고,
대입 연산자로 answer 변수에 값을 넣을 때 
`str(strLng/2)` 코드를 ( 으로 감싸니까 에러가 발생했다.
✏ bracket 표기법을 알게 되었는데,
> https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/String
> https://developer.mozilla.org/ko/docs/Web/JavaScript/A_re-introduction_to_JavaScript
> https://youngban.tistory.com/46
- ECMAScript 5 문법으로 문자열을 배열과 같은 오브젝트로 취급하여, 
문자에 해당하는 숫자 인덱스를 사용하는 방법이다.
- 브라켓([ ]) …
=> [1-15] 가운데 문자 출력

branch/IFR/[1-10]_문자_찾기.html, branch/IFR/[1-9]_A를_#으로.html
```
function solution(s){
let string  = s;
let result = [];
let sharp = "#"
for(let i=0; i<string.length-1; i++){
if(string[i]==="A"){
result.push(sharp);
}else{
result.push(string[i])
}
}
return result.join("");
}
let str="BANANA";
```
<br>
(문제 해결 과정)
<br>
<br>
result라는 배열을 만들어서, s의 원소가 A면 #을 result 배열에 푸시!
그 다음 join()을 사용하여, text로 변환하여 출력하였다.
(사진 첨부)
<br>
<br>
(메모 및 Tip)
=> [1-9] A를 #으로

branch/IFR/[1-10]_문자_찾기.html
```
function solution(s, t){
let result = 0;
for(let i=0; i<s.length; i++){
if(s[i]===t){
result++
}
}
return result;
}
let str="COMPUTERPROGRAMMING";
console.log(solution(str, 'R'));
```
<br>
(문제 해결 과정)
<br>
<br>
반복문을 통해 파라미터 s의 요소들의 값을 확인하고,
result에 결과를 담고, 출력한다.
(사진 첨부)
<br>
<br>
(메모 및 Tip)
=> [1-10] 문자 찾기

branch/IFR/[1-12]_대문자로_변환.html
```
function solution(s){  
let result=[];
for(let i=0; i<s.length; i++){
result.push(s[i].toUpperCase());
}
return result.join("");
}
console.log(solution("StuDY"));
```
<br>
(문제 해결 과정)
<br>
<br>
1.  맨 처음에는, 스트링의 요소 하나하나를 push하여 result 값을 보일 생각이였으나, 안되는 것을 느끼고 배열안에 넣고 join하기로 결정. 
2. if문을 사용하여 배열의 한 요소요소마다 대문자면 그대로 노출시키고, 대문자가 아니면 바꾸려했으나, 중간 꼬임으로 인해, 그냥 전체 문자를 대문자로 업데이트 개념으로 바꾸었다. 
(사진 첨부)
<br>
<br>
(메모 및 Tip)
=> [1-12] 대문자로 변환

branch/IFR/[1-13]_가장_긴_문자열.html
```
function solution(s){  
let stringsRength = [];
for(x of str){
stringsRength.push(x.length);
}
const maxStringsRength = Math.max(...stringsRength);
const answer = s.find(ele=>ele.length===maxStringsRength)
return answer;
}
let str=["teacher", "time", "student", "beautiful", "good"];
```
<br>
(문제 해결 과정)
<br>
<br>
하나의 배열을 만들어, 배열의 요소들의 길이값을 넣어두고, 
Math.max()를 사용하여 큰 값을 찾고, find()로 같은 길이값을 찾아서 결과도출
(사진 첨부)
<br>
<br>
(메모 및 Tip)
=> [1-13] 가장 긴 문자열

IFL/[1-1]_세_수_중_최솟값.html, IFL/test.txt, README.md
```js
function solution(a, b, c) {
let number = a;
if (a < b) {
number = a;
} else {
number = b;
}
if (number < c) {
return number;
} else {
return c;
}
}
console.log(solution(2, 5, 1));
```
<br>
(문제 해결 과정)
<br> 
if 문 사용 및 let 변수값 저장을 이용하여 최솟값을 구함
<br>
(사진 첨부)
<br>
<br>
(메모 및 Tip)
=> Ssammoo test

branch/IFR/[1-16]_중복문자제거.html
```js
function solution(s){ 
const answer = [...new Set(s)];
return answer.join("");
}
console.log(solution("ksekkset"));
```
<br />
<br /><br />
<br /><br />
<br /><br />
=> [1-16] 중복문자제거

branch/IFR/[1-17]_중복단어제거.html
```js
function solution(s){  
let answer = [... new Set(s)]
return answer;
}
let str=["good", "time", "good", "time", "student"];
```
<br />
<br /><br />
16번의 중복문자제거와 같은 방법을 사용하였음.
<br /><br />
<br /><br />
=> [1-17] 중복단어제거

branch/IFR/[2-1]_큰_수_출력하기.html
```js
function solution(arr){      
const randomNumber = Math.ceil(Math.random()*100)   
let answer = [] 
for(let i=0; i<arr.length; i++){
if(arr[i]>randomNumber) answer.push(arr[i])
}
return answer;
}
```
<br />
<br /><br />
100까지의 랜덤 숫자를 
<br /><br />
<br /><br />
=> [2-1] 큰 수 출력하기

branch/IFR/[2-3]_가위바위보.html
```js
function solution(a, b){         
let answer=[];
for(let i=0; i<a.length; i++){
if(a[i]===b[i]){
answer.push("D")
}else if(a[i]===1&&b[i]===2){
answer.push("B")
}else if(a[i]===1&&b[i]===3){
answer.push("A")
}else if(a[i]===2&&b[i]===1){
answer.push("A")
}else if(a[i]===2&&b[i]===3){
answer.push("B")
}else if(a[i]===3&&b[i]===1){
answer.push("B")
}else{
answer.push("A")
}
}
return answer;
}
let a=[2, 3, 3, 1, 3];
let b=[1, 1, 2, 2, 3];
console.log(solution(a, b));
```
<br />
<br /><br />
방법이 하드코딩 밖에 생각 안들어서, 열심히 ... 열심히 ... 🐥🐥
<br /><br />
<br /><br />
=> [2-3] 가위바위보

cheri/IFR/[2-4]_점수_계산.html
```js
function solution(arr){         
let answer=0, Points=0
for(let i=0; i<arr.length; i++){
if(arr[i]===1){
Points++;
answer+=Points
}else{
Points=0;
}
console.log(answer)
}
return answer;
}
let arr=[1, 0, 1, 1, 1, 0, 0, 1, 1, 0];
```
<br />
<br /><br />
for문을 사용하여 arr[i]가 1이면 점수를 1 올려서 
그대로 answer에 집어넣는 방식을 취하였습니다.
<br /><br />
<br /><br />
=> [2-4] 점수 계산

cheri/IFR/[2-5]_등수구하기.html
```js
function solution(arr){  
let answer=Array(arr.length).fill(1);
for(let i=0; i<arr.length; i++){
for(let j=0; j<arr.length; j++){
if(arr[i]<arr[j]) answer[i]++;
}
}             
return answer;
}
let arr=[87, 89, 92, 100, 76];
```
<br />
<br /><br />
https://cheri.tistory.com/105
<br /><br />
<br /><br />
=> [2-5] 등수구하기

cheri/IFR/[2-6]_격자판_최대합.html
```js
function solution(arr){  
let column = 0,
row = 0,
diagonal1 = 0,
diagonal2 = 0;
for(x of arr[1]){
row+=x
}
for(let y=0; y<arr.length; y++){
column+=arr[y][1];
}
for(let n=0; n<arr[0].length; n++){
diagonal1+=arr[n][n]
}
for(let i=0; i<arr[0].length; i++){
for(let j=arr[0].length-1; j>-1; j--){
if(i+j===4){
diagonal2+=arr[i][j]}
}
}
return Math.max(row,column,diagonal1,diagonal2);
}
let arr=[[10, 13, 10, 12, 15], 
[12, 39, 30, 23, 11],
[11, 25, 50, 53, 15],
[19, 27, 29, 37, 27],
[19, 13, 30, 13, 19]];
```
<br />
<br /><br />
<br /><br />
<br /><br />
=> [2-6] 격자판 최대합

cheri/IFR/[2-7]_봉우리.html, cheri/IFR/[3-1]_희문_문자열.html
```js
function solution(s) {
let answer = '',
string = s.toLowerCase();
for (let i = 0; i < s.length; i++) {
if (string[i] === string[string.length - 1 - i]) answer = 'Yes';
else answer = 'No';
}
return answer;
}
let str = 'gooG';
```
<br />
<br /><br />
매개변수를 소문자로 통일하고, 반복문을 이용하여 희문 문자열이 맞는지 확인한다.
<br /><br />
<br /><br />
=> [3-1] 희문 문자열

cheri/IFR/[3-2]_유효한_팰린드롬.html
```js
function solution(s) {
let str = s.replace(/[^(가-힣ㄱ-ㅎㅏ-ㅣa-zA-Z0-9)]/gi, '');
str = str.replace(/[0-9]/g, '').toLowerCase();
let answer = '';
for (let i = 0; i < Math.floor(str.length / 2); i++) {
if (str[i] === str[str.length - 1 - i]) answer = 'Yes';
else answer = 'No';
}
return answer;
}
let str = 'found7, time: study; Yduts; emit, 7Dnuof';
```
<br />
정규식을 이용하여, s의 특수문자, 띄어쓰기, 숫자를 제거 후,
for 반복문을 이용하여 팰린드롬 확인.
<br /><br />
<br /><br />
<br /><br />
=> [3-2] 유효한 팰린드롬

cheri/IFR/[3-3]_숫자만_추출.html
```js
function solution(str) {
const answer = str.replace(/[^0-9]/g, '');
return answer;
}
let str = 'g0en2T0s8eSoft';
```
<br />
정규식을 이용하여 str에서 바로 숫자만 추출
<br /><br />
<br /><br />
<br /><br />
=> [3-3] 숫자만 추출

cheri/IFR/[3-4]_가장_짧은_문자거리.html
```js
function solution(s, t) {
let answer = Array(s.length).fill(Number.MAX_SAFE_INTEGER);
const includeT = [];
//s 안의 t 문자좌표구하기
for (let i = 0; i < s.length; i++) {
if (s[i] === t) includeT.push(i);
}
//s의 인덱스에서 좌표값들을 뺀 결과값 중 제일 작은 숫자를 answer로 보내기.
//물론 음수가 있을 경우가 있으니 Math.abs를 통하여 절대값으로 변형해주었다.
for (let i = 0; i < includeT.length; i++) {
for (let j = 0; j < s.length; j++) {
if (answer[j] > Math.abs(j - includeT[i])) answer[j] = Math.abs(j - includeT[i]);
}
}
return answer;
}
let str = 'teachermode';
console.log(solution(str, 'e'));
```
<br />
코드에 주석으로 달아놓았다.
<br /><br />
<br /><br />
처음에는 indexOf나 match를 이용하여 t 문자 좌표를 구하려했으나, 
전체 좌표가 아닌 제일 앞에 있는 좌표만 구해졌었음. 
거기서 삽질 좀 함.. 🤔
<br /><br />
=> [3-4] 가장 짧은 문자거리

cheri/IFR/[3-5]_문자열_압축.html
```js
function solution(s) {
let answer = '',
repeat = 1;
for (let i = 0; i < s.length; i++) {
if (s[i] === s[i + 1]) repeat++;
else {
if (repeat === 1) repeat = '';
answer += `${s[i]}${repeat}`;
repeat = 1;
}
}
return answer;
}
let str = 'KKHSSSSSSSE';
```
<br />
반복값을 1로 지정해놓고, 요소와 요소+1을 비교해서 같으면 반복값을 누적, 같지 않으면, answer에 값을 넣고 초기화하는데, 결과값에 1이 들어가면안되니, 앞에 1일 경우에 repeat를 ''로 만들었다.
<br /><br />
<br /><br />
<br /><br />
=> [3-5] 문자열 압축

cheri/IFR/[4-1]_자리수의_합.html
```js
function solution(n, arr) {
let answer,
max = [0, 0];
for (let i = 0; i < n; i++) {
let sum = String(arr[i])
.split('')
.reduce((acc, cur) => acc + Number(cur), 0);
if (max[0] < sum) max = [sum, i];
if (max[0] === sum && arr[max[1]] < arr[i]) max = [sum, i];
}
answer = arr[max[1]];
return answer;
}
let arr = [128, 460, 603, 40, 521, 137, 123];
console.log(solution(7, arr));
```
<br />
1. 반복문을 사용해서 arr안의 요소들에 접근.
2. arr안의 요소를 문자열로 변환하고 한개씩 쪼개어 배열로 만들었음
3. reduce()를 사용하여 쪼갠 요소들의 값을 더하였음(이때 string으로 더하면 안되니 Number()을 사용하여 number인 상태로 더해주었음)
4. 그렇게 더한 각 arr 요소들의 더한 값을 max와 비교하여 max의 0번 인덱스보다 크면 max안에 sum의 값과, 인덱스를 넣었다. // max = [value, index]
5. max의 값과 sum이 같고, arr의 값이 더 크다면 max의 인덱스를 업데이트
6. answer에 arr[max[1]] 값을 넣었다.
<br /><br />
<br /><br />
<br /><br />
=> [4-1] 자리수의 합

cheri/IFR/[4-2]_뒤집은_소수.html
```js
<script>
function getPrimeNumber() {
let results = [];
// 1과 100사이의 숫자 중에 소수를 구하기 위한 반복문
for (let i = 2; i <= 100; i++) {
let isPrimeNumber = true;
for (let j = 2; j < i; j++) {
if (i % j === 0) {
isPrimeNumber = false;
}
}
// 소수이면 결과값에 할당
if (isPrimeNumber) {
results.push(i);
}
}
return results;
}
function solution(arr) {
let answer = [];
for (let x of arr) {
let value = x,
sum = 0;
while (value) {
sum = sum * 10 + (value % 10);
value = Math.floor(value / 10);
}
for (let i = 0; i < getPrimeNumber().length; i++) {
if (sum === getPrimeNumber()[i]) answer.push(sum);
}
}
return answer;
}
let arr = [32, 55, 62, 20, 250, 370, 200, 30, 100];
```
<br />
검색을 통하여, 1~100사이의 소수들을 뽑아내는 코드를 긁어왔다.
그대로 긁어온 값을 이용하여, 뒤집은 숫자가 소수가 맞는지 
하나씩 대입해보며, answer에 누적시켰다.
<br /><br /> …
=> [4-2] 뒤집은 소수

cheri/IFR/[4-2]_뒤집은_소수.html, cheri/IFR/[4-3]_멘토링.html
```js
function solution(arr) {
let answer = [];
for (let i = 0; i < arr.length; i++) {
let nTest = arr[i];
if (i === 0) {
for (let x = 0; x < nTest.length - 1; x++) {
for (let y = x + 1; y < nTest.length; y++) {
answer.push([nTest[x], nTest[y]]);
}
}
} else {
let prevArr = [...answer];
answer = [];
for (let x = 0; x < prevArr.length; x++) {
let first = prevArr[x][0];
let second = prevArr[x][1];
if (nTest.indexOf(first) < nTest.indexOf(second)) {
answer.push([first, second]);
}
}
}
}
console.log(answer);
return answer.length;
}
let arr = [
[3, 4, 1, 2],
[4, 3, 2, 1],
[3, 1, 4, 2],
];
```
<br />
결국 풀지 못해, 강의를 보았다.
강의를 보고, 구글링도 했지만 이해하지 못했다...
넘어야 할 산이 생겼도다... 
<br /><br />
<br /><br />
<br /><br />
=> Cheri test

cheri/IFR/[4-4]_졸업선물.html
```js
function solution(m, product) {
let answer = 0;
const n = product.length;
//배열 정렬
product.sort((a, b) => a[0] + a[1] - (b[0] + b[1]));
for (let i = 0; i < n; i++) {
//할인할 값은 제일 물건값이 많이 나가는 것으로 선택한다.
//가지고 있는 돈에서 할인된 물건 값을 먼저 빼고, 물건을 하나 샀으니 카운팅한다.
let change = m - (product[i][0] / 2 + product[i][1]);
//구입한 물건을 카운팅한다.
let cnt = 1;
for (let j = 0; j < n; j++) {
//쓸 수 있는 돈보다 물건의 값이 크면 break!
if (j !== i && product[j][0] + product[j][1] > change) break;
//쓸 수 있는 돈보다 물건의 값이 작거나 같으면 물건의 값을 뺀다.
if (j !== i && product[j][0] + product[j][1] <= change) {
change -= product[j][0] + product[j][1];
//물건을 구입했으니 카운트!
cnt++;
}
}
//answer과 cnt의 값을 확인하고 큰 값을 answer에 넣는다.
answer = Math.max(answer, cnt);
}
return answer;
}
let arr = [
[6, 6],
[2, 2],
[4, 3],
[4, 5],
[10, 3],
];
console.log(solution(28, …
```
=> [4-4] 졸업선물

cheri/IFR/[4-5]_K번째_큰_수.html
```js
function solution(n, k, card) {
let answer;
let arr = [];
//경우의 수 대입
for (let i = 0; i < n; i++) {
for (let j = 0; j < n; j++) {
for (let k = 0; k < n; k++) {
if ((i < j) & (j < k)) arr.push(card[i] + card[j] + card[k]);
}
}
}
//중복 제거
arr = new Set(arr);
//Set을 Array로 변환하고 내림차순으로 정렬
let sortArr = Array.from(arr).sort((a, b) => b - a);
answer = sortArr[2];
return answer;
}
let arr = [13, 15, 34, 23, 45, 65, 33, 11, 26, 42];
console.log(solution(10, 3, arr));
```
<br />
<br /><br />
<br /><br />
배열로 돌리지 않고, new Set을 만들고 add로 추가해줘도 되는 방식이 있다는 것을 알았다.
<br /><br />
=> [4-5] K번째 큰 수

ssammoo/BOJ/BOJ_10869.py, ssammoo/BOJ/BOJ_2588.py
```
a = int(input())
b = int(input())
b_100 = b // 100
b_10 = (b - b_100 * 100) // 10
b_1 = (b - b_100*100 - b_10 * 10)
print(a * b_1)
print(a * b_10)
print(a * b_100)
print((b_100*100 + b_10 * 10 + b_1) * a)
```
123
456
738  
615  
492  
56088
<br /><br />
=> [BOJ, 2588] 곱셈

ssammoo/BOJ/BOJ_1110.py
```
input_value = int(input()) # 0 < <=99
repeat_value = input_value
result = 0
confirm = True
while confirm == True :
repeat_10 = repeat_value // 10
repeat_1 = repeat_value % 10
repeat_plus = (repeat_10 + repeat_1) % 10
result += 1
repeat_value = repeat_1 * 10 + repeat_plus
if repeat_value == input_value :
confirm = False
print(result)
```
26
4
<br /><br />
while문 조건 제대로 쓸것..
=> [BOJ, 1110] 더하기 사이클

.gitignore, .vscode/launch.json, .vscode/settings.json, ssammoo/BOJ/BOJ_4344.py
```
case_num = int(input())
for each_case in range(case_num) :
list_for_num = list(map(lambda each : int(each), input().split(" ")))
average = sum(list_for_num[1:]) / list_for_num[0]
count = 0
for count_person in list_for_num[1:] :
if count_person > average :
count += 1
result = count/list_for_num[0]*100
print(f"{result:.3f}%")
```
<br />
1 (넣어야하는 자료의 개수)
5 50 50 70 80 100 (개수별 출력)
40.000%
<br /><br />
<br /><br />
처음에 왜 틀렸다고 나오는지 모르겠지만 단순화 하여 성공
<br /><br />
=> [BOJ, 4344] 평균은 넘겠지

ssammoo/BOJ/BOJ_4344.py, ssammoo/BOJ/BOJ_4673.py
```js
```
<br />
<br /><br />
<br /><br />
<br /><br />
=> [BOJ, 4673] 셀프 넘버

ssammoo/BOJ/BOJ_1157.py
```
alpha = input().upper()
alpha_dict = {}
for each in alpha.upper() :
if each in alpha_dict :
alpha_dict[each] += 1
else :
alpha_dict[each] = 1
return_alpha = ""
max_num = 0
for each in alpha_dict :
if alpha_dict[each] > max_num :
max_num = alpha_dict[each]
return_alpha = each
elif alpha_dict[each] == max_num :
return_alpha = "?"
print(return_alpha)
```
<br />
- sadsczQRQRdas
- S
<br /><br />
<br /><br />
딕셔너리를 사용해 키를 문자 값으로 밸류값을 중복숫자로 저장
<br /><br />
=> [BOJ, 1157] 단어 공부

ssammoo/BOJ/BOJ_2941.py
```
input_alpha = input()
cro_alpha = [
"c=",
"c-",
"dz=",	
"d-",
"lj",
"nj",
"s=",
"z="
]
for each in cro_alpha :
if each in input_alpha :
input_alpha = input_alpha.replace(each, "a")
print(len(input_alpha))
```
<br />
- ljes=njak
- 6
<br /><br />
<br /><br />
- 너무 어렵게 생각해서 코드가 길어졌다가 다른 사람답보고 고친케이스..
- 앞으로 문제를 명확히 해서 간결하게 풀어나가는 연습을 해야할것
<br /><br />
=> [BOJ, 2941] 크로아티아 알파벳

ssammoo/BOJ/BOJ_1316.py, ssammoo/BOJ/BOJ_2941.py
```
input_num_val = int(input())
checker_num = 0
for each in range(input_num_val) :
input_val = input()
for each_index in range(len(input_val) - 1):
if input_val[each_index] != input_val[each_index + 1]:
if input_val[each_index] in input_val[each_index + 1:] :
checker_num -= 1
break
checker_num += 1
```
<br />
3
happy
new
year
3
<br /><br />
<br /><br />
- 어떻게 떨어져 있는 문자를 확인할 것인지가 관건이었던 문제
- 리스트를 잘라서 뒤에 있는 문자를 확인하는 방법은 생각도 못했었다.
- 다음에 꼭 응용해 볼 수 있었으면 하는 마음
<br /><br />
=> [BOJ, 1316] 그룹 단어 체커

ssammoo/BOJ/BOJ_2839.py
```
input_weight = int(input())
sugar_bags = 0
while input_weight >= 0 :
if input_weight % 5 == 0 :
sugar_bags = sugar_bags + input_weight // 5
print(sugar_bags)
break
input_weight -= 3
sugar_bags += 1
if input_weight < 0 :
print("-1")
```
<br />
- 5로 나누어 떨어지지 않을떄 3을 뺴가며 무게를 0으로 맞추는 작업
<br /><br />
<br /><br />
- 단순하게 해답을 찾아냈다고 생각했을떄 한번 더 생각해볼 것
- 여러개의 반복이 있을떄 반복하지 않을 경우 어떻게 해야할지 생각해 볼 것
<br /><br />
=> [BOJ, 2839]

ssammoo/BOJ/BOJ_1011.py
```
import math
case_num = int(input())
for each in range(case_num):
from_x, from_y = input().split()
from_x = int(from_x)
from_y = int(from_y)
distance = from_y - from_x
count = 0
floor_root_dis = math.floor(math.sqrt(distance))
source_num =floor_root_dis ** 2
if distance > source_num and distance <= source_num + floor_root_dis :
count = floor_root_dis * 2
elif distance > source_num + floor_root_dis :
count = floor_root_dis * 2 + 1
elif distance == source_num :
count = floor_root_dis * 2 - 1
if distance < 4 : 
count = distance
print(count)
```
<br />
- 조건대로 하나하나 값을 표로 제작
- 표 제작 후 규칙을 찾아 이를 식으로 나타냄
<br /><br />
<br /><br />
- 규칙찾는게 너모 어렵다
<br /><br />
=> [BOJ, 1011] Fly to the Alpha Centauri

ssammoo/BOJ/BOJ_4948.py
```
import math
import sys
nat_num = 123456
mul_num = 2 * nat_num
prime_arr = []
for each in range(2, mul_num + 1):
prime_confirm = 0
for each_prime in range(2, int(math.sqrt(each))+1):
if each % each_prime == 0:
prime_confirm += 1
break
if prime_confirm == 0 :
prime_arr.append(each)
num = int(sys.stdin.readline())
while num != 0:
count = 0
for i in prime_arr:
if num < i <= num * 2:
count += 1
print(count)
num = int(sys.stdin.readline())
```
<br />
- 시간초과 문제로 소수의 배열을 미리 만들어 검색하도록함
<br /><br />
<br /><br />
- 시간복잡도의 중요성
<br /><br />
=> [BOJ, 4948] 베르트랑 공준

ssammoo/BOJ/BOJ_1436.py
```
input = int(input())
count = 0
start_num = 666
while True :
if "666" in str(start_num):
count += 1
if count == input :
break
start_num += 1
print(start_num)
```
<br />
- 666, 1666, 2666, 3666, 4666, 5666, 6660, 6661 순서임...
<br /><br />
<br /><br />
- 문제에 낚이지 말자
<br /><br />
=> [BOJ, 1436] 영화감독 숌

ssammoo/BOJ/BOJ_2869.py
```
to_up, to_down, height = input().split()
to_up = int(to_up)
to_down = int(to_down)
height = int(height)
different_day = to_up - to_down
final_different = height - to_up
if final_different % different_day != 0 :
day = 1 + (final_different//different_day +  1)
else :
day = 1 + final_different//different_day
print(day)
""" 
sum_height = 0
days = 0
while sum_height <= height :
sum_height = sum_height + to_up
if sum_height >= height :
days += 1
break
else :
days += 1
sum_height = sum_height - to_down
print(days) 
"""
```
<br />
- 규칙성을 토대로 알고리즘 작성
- 아래코드는 반복문 코드
<br /><br />
<br /><br />
- 규칙성을 찾으면 코드가 빨라진다
<br /><br />
=> [BOJ, 2869] 달팽이는 올라가고 싶다

ssammoo/BOJ/BOJ_1037.py
```
ea_num = int(input())
real_arr = input().split()
to_num_arr = []
for each in real_arr :
to_num_arr.append(int(each))
to_num_arr.sort()
result = to_num_arr[0] * to_num_arr[-1]
print(result)
```
<br />
없다
<br /><br />
<br /><br />
너무 쉬워서 어처구니 없는 문제(15번째 문제였음)
<br /><br />
=> [BOJ, 1037] 약수

ssammoo/BOJ/BOJ_2609.py
```
import math
input_val = input().split()
to_int = []
left = set()
right = set()
for each in input_val :
to_int.append(int(each))
for each in range(1, to_int[0] + 1):
if to_int[0] % each == 0 :
left.add(each)
for each in range(1, to_int[1] + 1):
if to_int[1] % each == 0 :
right.add(each)  
left_and_right = list(left & right)
left_and_right.sort()
measure = left_and_right[-1]
common_multi = int(to_int[0] * to_int[1] / measure) 
print(measure)
print(common_multi)
```
<br />
개념만 파악할 것
<br /><br />
<br /><br />
<br /><br />
=> [BOJ, 2609] 최대공약수와 최소공배수

ssammoo/BOJ/BOJ_10250.py
```
import math
repeat_num = int(input())
for each in range(repeat_num):
input_val = input().split()
to_int = []
for each_inner in input_val :
to_int.append(int(each_inner))
nth_floor = to_int[2] % to_int[0]
if nth_floor == 0 :
nth_floor = to_int[0]
arc = math.ceil(to_int[2] / to_int[0])
if arc <= to_int[1] :
if arc < 10 :
address = str(nth_floor) + "0" + str(arc)
else :
address = str(nth_floor) + str(arc)
print(address)
```
<br />
관계식 유도하기
<br /><br />
<br /><br />
반복문에 고정하지 말고 관계식을 유도할것
<br /><br />
=> [BOJ, 10250] ACM 호텔

ssammoo/BOJ/BOJ_1929.py
```
import math
insert_val = input().split()
to_int = []
prime_arr = []
for each in insert_val:
to_int.append(int(each)) 
for each in range(2, to_int[1] + 1):
check_for_prime = 0
for each_inner in range(2, int(math.sqrt(each))+1):
if each % each_inner == 0:
check_for_prime += 1
break
if check_for_prime == 0 :
prime_arr.append(each)
for result in prime_arr:
if to_int[0] <= result :
print(result)
```
<br />
무엇보다도 시간복잡도를 줄이는 것이 관건 
<br /><br />
<br /><br />
시간복잡도를 줄이기 위해 루트를 씌워줌
<br /><br />
=> [BOJ, 1929] 소수 구하기

ssammoo/BOJ/BOJ_11729.py
```
def top_of_hanoi (n, first, second, third):
if n == 1 :
total_num.append(first + " " + third)
return 
top_of_hanoi(n - 1, first, third, second)
total_num.append(first + " " + third)
top_of_hanoi(n - 1, second, first, third)
total_num = []
top_of_hanoi(input_val, "1", "2", "3")
print(len(total_num))
for each in total_num:
print(each)
```
<br />
- 유투브 참고
- https://www.youtube.com/watch?v=FYCGV6F1NuY
<br /><br />
<br /><br />
- 재귀함수를 이용할 때는 최대한 단순한 숫자부터 시작할 것
<br /><br />
=> [BOJ, 11729] 하노이 탑 이동 순서

ssammoo/BOJ/BOJ_11651.py
```
array_ea = int(input())
input_arr = []
for each in range(array_ea):
x, y = map(int, input().split() )
input_arr.append([y, x])
input_arr.sort()
for y, x  in input_arr :
print(x, y)
```
<br />
- 정렬은 sort로
<br /><br />
<br /><br />
<br /><br />
=> [BOJ 11651] 좌표 정렬하기 2

ssammoo/BOJ/BOJ_11651.py, ssammoo/BOJ/BOJ_2805.py
```
tree, need = map(int, input().split())
tree_forest = list(map(int, input().split()))
start = 1
end = max(tree_forest)
while start <= end :
mid = (start + end) // 2
total_meter = sum(i-mid if i > mid else 0 for i in tree_forest)
if total_meter >= need :
start = mid + 1
else :
end = mid - 1
print(end)
```
<br />
나무의 잘라낸 길이를 기준으로 잡고 이분탐색 진행
<br /><br />
<br /><br />
한 문제 더 풀것
<br /><br />
=> [BOJ, 2805] 나무자르기

ssammoo/BOJ/BOJ_10828.py, ssammoo/BOJ/BOJ_11651.py
```
import sys
input_num = int(sys.stdin.readline())
stack_arr =[]
for each in range(input_num):
input_arr = sys.stdin.readline().split()
len_stack = len(stack_arr)
keyword = input_arr[0]
if keyword == "push" :
stack_arr.append(int(input_arr[1]))
if keyword == "pop":
if len_stack == 0 :
print("-1")
else :
print(stack_arr.pop())
if keyword == "size":
print(len_stack)
if keyword == "empty":
if len_stack == 0 :
print("1")
else :
print("0")
if keyword == "top":
if len_stack == 0 :
print("-1")
else :
print(stack_arr[-1])
```
<br />
스택개념만 알고있으면 문제 없음
<br /><br />
<br /><br />
stdin 쓸것
<br /><br />
=> [BOJ, 10828] 스택

ssammoo/BOJ/BOJ_10773.py, ssammoo/BOJ/BOJ_11651.py
```
import sys
input_num = int(sys.stdin.readline())
stack_array = []
for each in range(input_num):
input_value = int(sys.stdin.readline())
if input_value == 0 :
stack_array.pop()
else :
stack_array.append(input_value)
sum_total = sum(stack_array)
print(sum_total)
```
<br />
<br /><br />
<br /><br />
<br /><br />
=> [BOJ, 10773] 제로

ssammoo/BOJ/BOJ_9012.py
```
import sys
input_num = int(sys.stdin.readline())
for each in range(input_num):
parentheis = sys.stdin.readline()
parentheis_arr = []
for each_parentheis in parentheis :
parentheis_arr.append(each_parentheis)
parentheis_arr.pop()
arr_len =len(parentheis_arr)
sum = 0
for each in parentheis_arr :
if each == "(":
sum += 1
elif each == ")" :
sum -= 1
if sum < 0 :
print("NO")
break
if sum > 0 :
print("NO")
elif sum == 0 :
print("YES")
```
<br />
<br /><br />
<br /><br />
- 조건 하나 못찾았었음..
<br /><br />
=> [BOJ, 9012] 괄호

ssammoo/BOJ/BOJ_1934.py
```
import sys
how_many = int(sys.stdin.readline())
def gcd(a, b):
mod = a % b
while mod > 0 :
a = b
b = mod
mod = a % b
return b
def lcm(a, b):
return a * b // gcd(a, b)
for each in range(how_many) :
a, b = map(int, sys.stdin.readline().split())
print(lcm(a, b))
""" import sys
how_many = int(sys.stdin.readline())
def make_multiple_arr(num) :
multiple_arr = []
for each in range(1,num + 1) :
if num % each == 0 :
multiple_arr.append(each)
return multiple_arr
for each in range(how_many) :
a, b = map(int, sys.stdin.readline().split())
left_multiple = set(make_multiple_arr(a))
right_multiple = set(make_multiple_arr(b))
equal_multiple_arr = list(left_multiple & right_multiple)
equal_multiple_arr.sort()
equal_multiple = equal_multiple_arr[-1]
min_multiple = int(a * b / equal_multiple) …
```
=> [BOJ, 1934] 최소공배수

ssammoo/BOJ/BOJ_11050.py
```
from math import factorial
n, k = map(int, input().split())
b = factorial(n) // (factorial(k) * factorial(n - k))
print(b)
```
<br />
<br /><br />
<br /><br />
<br /><br />
=> [BOJ, 11050] 이항계수

ssammoo/BOJ/BOJ_1010.py
```python
import sys
repeat_num = int(sys.stdin.readline())
def factorial (n) :
if n <= 1 :
return 1
return n * factorial(n - 1)
for each in range(repeat_num):
N, M = map(int, sys.stdin.readline().split())
bridge_num = factorial(M) / (factorial(N) * factorial(M-N))
print(int(bridge_num))
```
{문제풀이과정}
조합문제
=> [BOJ, 1010] 다리 놓기

ssammoo/BOJ/BOJ_4949.py
```python
while True :
word = input()
if word == ".":
break
stack_arr = []
confirm = True
for each_alpha in word :
if each_alpha == "(" or each_alpha == "[" :
stack_arr.append(each_alpha)
elif each_alpha == ")" :
if len(stack_arr) == 0 or stack_arr[-1] == "[":
confirm = False
break
elif stack_arr[-1] == "(":
stack_arr.pop()
elif each_alpha == "]" :
if len(stack_arr) == 0 or stack_arr[-1] == "(":
confirm = False
break
elif stack_arr[-1] == "[":
stack_arr.pop()
if confirm == True and len(stack_arr) == 0 :
print("yes")
else:
print("no")
```
{문제풀이과정}
스택을 사용할것
=> [BOJ, 4949] 균형잡힌 세상

ssammoo/BOJ/BOJ_1874.py
```python
repeat_val = int(input())
numbers_arr = [] # 1 ~ repeat
operations_arr = []
to_stack_num = 1
temp = True
for each in range(repeat_val):
while to_stack_num <= input_val :
numbers_arr.append(to_stack_num)
operations_arr.append("+")
to_stack_num += 1
if numbers_arr[-1] == input_val :
numbers_arr.pop()
operations_arr.append("-")
else :
temp = False
if temp == False :
print("NO")
else :
for each in operations_arr :
print(each)
```
{문제풀이과정}
- 순서를 그릴것
- 어떻게 구현할 지 생각할것
- 위의 경우 for 문 마다 인풋값을 받아 즉시 비교처리
=> [BOJ, 1874] 스택 수열

ssammoo/BOJ/BOJ_1021.py
```python
queue_len, target_len = map(int, input().split())
target_arr = list(map(int, input().split()))
queue = []
count = 0
for each in range(1, queue_len + 1 ) :
queue.append(int(each))
for target in target_arr :
queue_half_index = (len(queue) - 1) // 2 
target_index = queue.index(target)
if queue_half_index >= target_index :
while True:
if queue[0] == target :
queue.pop(0)
break
else :
queue.append(queue.pop(0))
count += 1
else :    
while True:
if queue[0] == target :
queue.pop(0)
break
else:
queue.insert(0, queue.pop())
count += 1
print(count)
```
{문제풀이과정}
- 손으로 써내려가면서 규칙을 발견
=> [BOJ, 1021] 회전하는 큐

ssammoo/BOJ/BOJ_18258.py
```python
import sys
from collections import deque
repeat_val = int(sys.stdin.readline())
queue = deque([])
for repeat in range(repeat_val):
command_str = sys.stdin.readline()
command_arr = list(command_str.split())
command_key = command_arr[0]
if command_key == "push" :
queue.append(int(command_arr[1]))
if command_key == "pop" :
if len(queue) == 0 :
print("-1")
else :
print(queue.popleft())
if command_key == "size" :
print(len(queue))
if command_key == "empty":
if len(queue) == 0 :
print("1")
else : 
print("0")
if command_key == "front" :
if len(queue) == 0 :
print("-1")
else :
print(queue[0])
if command_key == "back" :
if len(queue) == 0 :
print("-1")
else :
print(queue[-1])
```
{문제풀이과정}
- 시간 단축위해 sys 쓸것
- 동일하게 deque 쓸것
=> [BOJ, 18258] 큐2

ssammoo/BOJ/BOJ_1260.py
```python
total_node, total_line, start_num = map(int,input().split())
graph_matrix = [[0]* (total_node + 1) for each in range(total_node + 1)]
for each in range(total_line) :
x, y = map(int, input().split())
graph_matrix[x][y] = 1
graph_matrix[y][x] = 1
def BFS(start_num, visited) :
visited.append(start_num)
for node in range(len(graph_matrix[start_num])) :
if graph_matrix[start_num][node] == 1 and node not in visited :
BFS(node, visited)
return visited
def DFS(start_num) :
queue = [start_num]
visited = [start_num]
while queue :
current_node = queue.pop(0)
for node in range(len(graph_matrix[start_num])) :
if graph_matrix[current_node][node] == 1 and node not in visited :
queue.append(node)
visited.append(node)
return visited
print(*BFS(start_num, []))
print(*DFS(start_num))
```
{문제풀이과정} …
=> [BOJ, 1260] DFS와 BFS

ssammoo/BOJ/BOJ_2108.py
```python
import sys
from collections import Counter
input_command_num = int(input())
arr = []
for each in range(input_command_num) :
input = int(sys.stdin.readline())
arr.append(input)
arr.sort()
numbers = Counter(arr).most_common()
arithmetic_mean = round((sum(arr) / len(arr)))
middle_value = arr[len(arr) // 2]
print(arithmetic_mean)
print(middle_value)
if len(numbers) > 1 :
if numbers[0][1] == numbers[1][1] :
print(numbers[1][0])
else :
print(numbers[0][0])
else :
print(numbers[0][0])
print(arr[-1]-arr[0])
```
{문제풀이과정}
- Counter 함수 사용 안할시 시간초과되어 버림
=> [BOJ, 2108] 통계학

ssammoo/BOJ/BOJ_2630.py
```python
n = int(input())
arr = [list(map(int, input().split())) for each in range(n)]
white, blue = 0, 0
def check (x, y, n) :
paper_color = arr[x][y]
for x_val in range(x, x + n):
for y_val in range(y, y + n):
if arr[x_val][y_val] != paper_color:
return False
return True
def count_paper(x, y, n) :
global white, blue
if check(x, y, n) :
if arr[x][y] == 1 :
blue += 1
else :
white += 1
else :
half = n // 2
count_paper(x, y, half)
count_paper(x + half, y , half)
count_paper(x, y + half, half)
count_paper(x + half, y + half, half)
count_paper(0,0,n)
print(white)
print(blue)
```
{문제풀이과정}
=> [BOJ, 2630] 색종이 만들기

ssammoo/BOJ/BOJ_15649.py, ssammoo/BOJ/BOJ_15650.py
```python
n, m = map(int, input().split())
stack = []
def back_tracking(start_num) :
if len(stack) == m :
print(*stack)
return
for each in range(1, n + 1):
if each in stack :
continue
if start_num <= each :
stack.append(each)
back_tracking(each)
stack.pop()        
back_tracking(1)
```
{문제풀이과정}
- 트리구조로 만든 후 규칙을 찾아낼 것
=> [BOJ, 15650] N과 M 2

ssammoo/BOJ/BOJ_9663.py
```python
stack= [0] * N
count = 0
def checker(start_num) :
for node in range(start_num) :
if stack[start_num] == stack[node] or (start_num - node) == abs(stack[start_num] - stack[node]) :
return False
return True
def back_tracking_queen(start_num) :
global count
if start_num == N :
count += 1
return
else :
for node in range(N):
stack[start_num] = node
if checker(start_num):
back_tracking_queen(start_num+ 1)
back_tracking_queen(0)
print(count)
```
{문제풀이과정}
- 언어세팅 pypy3로 해야 시간초과 안남
=> [BOJ, 9663] N-Queen

ssammoo/BOJ/BOJ_2579.py
```python
n = int(input())
stair = [0] * 300
for each in range(n) :
stair[each] = int(input())
dp = [0] * 300
dp[0] = stair[0]
dp[1] = stair[0] + stair[1]
dp[2] = max(stair[2] + stair[0], stair[2] + stair[1] )
for each in range(3, n) :
dp[each] = max(dp[each - 3] + stair[each - 1] + stair[each], dp[each - 2] + stair[each])
print(dp[n - 1])
```
{문제풀이과정}
=> [BOJ, 2579] 계단 오르기

ssammoo/BOJ/BOJ_1002.py
```python
import math
test_case = int(input())
for each in range(test_case) :
data = list(map(int, input().split()))
abs_x = abs(data[0]-data[3])
abs_y = abs(data[1]-data[4])
distance_1_2 = math.sqrt(abs_x ** 2 + abs_y ** 2)
sum_r = data[2] + data[5]
minus_r = abs(data[2] - data[5])
if distance_1_2 == 0 :
if data[2] == data[5] :
print(-1)
else :
print(0)
elif sum_r == distance_1_2 or minus_r == distance_1_2 :
print(1)
elif sum_r > distance_1_2 and minus_r < distance_1_2  :
print(2)
else :
print(0)
```
{문제풀이과정}
- 피타고라스
=> [BOJ, 1002] 터렛

ssammoo/BOJ/BOJ_2798.py
```python
length, aim = map(int,input().split())
arr = list(map(int, input().split()))
aim_arr = []
for each in arr :
for each_in in arr :
for each_inin in arr :
if each + each_in + each_inin <= aim and each != each_in and each != each_inin and each_in != each_inin:
aim_arr.append(each + each_in + each_inin)
aim_arr.sort()
print(aim_arr[-1])
```
{문제풀이과정}
=> [BOJ, 2798] 블랙잭

ssammoo/BOJ/BOJ_2231.py
```python
arr = []
for each in range(1, input_val + 1) :
number_arr = list(map(int, str(each)))
sum_each = each + sum(number_arr)
if sum_each == input_val :
arr.append(each)
try :
print(arr[0])
except :
print(0)
```
{문제풀이과정}
=> [BOJ, 2231] 분해합

ssammoo/BOJ/BOJ_1003.py
```python
import sys
dp_0 = [0] * 41
dp_1 = [0] * 41
dp_0[0] = 1
dp_1[1] = 1
for each in range(2, 41) :
dp_0[each] = dp_0[each - 2] + dp_0[each - 1]
dp_1[each] = dp_1[each - 2] + dp_1[each - 1]
for each in range(input_val):
each_input = int(sys.stdin.readline())
print(dp_0[each_input], dp_1[each_input])
```
{문제풀이과정}
=> [BOJ, 1003] 피보나치 함수

ssammoo/BOJ/BOJ_1541.py
```python
input_equation = list(map(str,input().split("-")))
arr_for_sum = []
arr_for_sum.append(sum(list(map(int,input_equation[0].split("+")))))
for each in range(1, len(input_equation)):
plus_sum = sum(list(map(int,input_equation[each].split("+"))))
arr_for_sum.append(-plus_sum)
print(sum(arr_for_sum))    
```
{문제풀이과정}
=> [BOJ, 1541] 잃어버린 괄호

ssammoo/BOJ/BOJ_11866.py
```python
total_arr, K = map(int, input().split())
arr = []
for each in range(1, total_arr + 1) :
arr.append(each)
save_yose = []
print("<", end="")
K_index = 0
while len(arr) > 1 :
K_index = K_index + K
if K_index > len(arr):
K_index = K_index % len(arr)
if K_index == 0 :
K_index = K_index + len(arr)
K_index = K_index - 1
print(str(arr.pop(K_index)), end=", ")
print("{}>".format(str(arr.pop())))
```
{문제풀이과정}
- 인덱스면 인덱스로 통일할 것
=> [BOJ, 11866] 요세푸스 문제0

ssammoo/BOJ/BOJ_9184.py
```python
import sys
def w(a, b, c):
if a <= 0 or b <= 0 or c <= 0:
return 1
elif a > 20 or b > 20 or c > 20:
return w(20, 20, 20)
if dp[a][b][c] :
return dp[a][b][c]
if a<b<c :
dp[a][b][c] = w(a,b,c-1) + w(a,b-1,c-1) - w(a,b-1,c)
else:
dp[a][b][c] = w(a-1,b,c) + w(a-1,b-1,c) + w(a-1,b,c-1) - w(a-1,b-1,c-1)
return dp[a][b][c]
dp = [[[0 for _ in range(21)] for _ in range (21)] for _ in range (21)]
while True:
a,b,c = map(int, sys.stdin.readline().split())
if a==-1 and b==-1 and c==-1:
break
print("w({}, {}, {}) = {}".format(a,b,c,w(a,b,c)))
```
{문제풀이과정}
=> [BOJ, 9184] 신나는 함수 실행

ssammoo/BOJ/BOJ_9461.py
```python
dp_arr =[0] * 101
dp_arr[0] = 1
dp_arr[1] = 1
dp_arr[2] = 1
dp_arr[3] = 2
dp_arr[4] = 2
for each in range(5, 101) :
dp_arr[each] = dp_arr[each - 1] + dp_arr[each - 5]
print(dp_arr[input_val - 1])
```
{문제풀이과정}
=> [BOJ, 9461] 파도반 수열

ssammoo/BOJ/BOJ_1149.py
```python
import sys
cost_arr = []
each_cost = list(map(int, sys.stdin.readline().split()))
cost_arr.append(each_cost)
for cost_index in range(1, len(cost_arr)) :
cost_arr[cost_index][0] = cost_arr[cost_index][0] + min(cost_arr[cost_index - 1][1], cost_arr[cost_index - 1][2])
cost_arr[cost_index][1] = cost_arr[cost_index][1] + min(cost_arr[cost_index - 1][0], cost_arr[cost_index - 1][2])
cost_arr[cost_index][2] = cost_arr[cost_index][2] + min(cost_arr[cost_index - 1][1], cost_arr[cost_index - 1][0])
print(min(cost_arr[len(cost_arr) - 1][0], cost_arr[len(cost_arr) - 1][1], cost_arr[len(cost_arr) - 1][2]))
```
{문제풀이과정}
=> [BOJ, 1149] RGB거리

ssammoo/BOJ/BOJ_11047.py
```python
N, K = map(int, input().split())
value_arr = []
value_arr.append(input_val)
coin_count = 0
for coin_val_index in range(len(value_arr) -1, -1, -1) :
if K < value_arr[coin_val_index] :
continue
else :
remain = K % value_arr[coin_val_index]
coin_count += K // value_arr[coin_val_index]
K = remain
if N == 0 :
break
print(coin_count)
```
{문제풀이과정}
=> [BOJ, 11047] 동전 0

ssammoo/BOJ/BOJ_11399.py
```python
time_arr = list(map(int, input().split()))
time_arr.sort()
total_time = 0
for each_index in range(N):
total_time += sum(time_arr[:each_index + 1])
print(total_time)
```
{문제풀이과정}
=> [BOJ, 11399] ATM

ssammoo/BOJ/BOJ_2606.py
```python
computer_num = int(input())
connect_num = int(input())
graph = [[0] * (computer_num + 1) for i in range(computer_num + 1)]
for each in range(connect_num):
val_x, val_y = map(int, input().split())
graph[val_x][val_y] = 1
graph[val_y][val_x] = 1
start_computer = 1
def DFS(start_num, graph_arr) :
stack = [start_num]
visited = [start_num]
while stack :
current_node = stack.pop()
for graph_node in range(len(graph_arr[current_node])) :
if graph_arr[current_node][graph_node] == 1 and graph_node not in visited :
stack.append(graph_node)
visited.append(graph_node)
return visited
visited_arr = DFS(start_computer, graph)
print(len(visited_arr) - 1)
```
{문제풀이과정}
=> [BOJ, 2606] 바이러스

ssammoo/BOJ/BOJ_11279.py
```python
import sys
import heapq
heap = []
input_val = int(sys.stdin.readline())
if input_val == 0 :
if len(heap) != 0 :
print(-(heapq.heappop(heap)))
else :
print(0)
else :
heapq.heappush(heap, -input_val)
```
{문제풀이과정}
=> [BOJ, 11279] 최대힙

ssammoo/BOJ/BOJ_1927.py
```python
import sys
import heapq
heap = []
input_val = int(sys.stdin.readline())
if input_val == 0 :
if len(heap) != 0 :
print(heapq.heappop(heap))
else :
print(0)
else :
heapq.heappush(heap, input_val)
```
{문제풀이과정}
- 객기부리지말고 모듈 사용할것
=> [BOJ, 1927] 최소힙

ssammoo/BOJ/BOJ_2667.py
```python
complex_arr = []
dx = [-1, 0, 1, 0] # 북 동 남 서 순(css 규칙, 시계방향)
dy = [0, 1, 0, -1]
input_arr = list(input())
complex_arr.append(input_arr)
count_arr = []
def BFS(x, y) :
queue = [[x, y]]
complex_arr[x][y] = "0"
count = 1
while queue :
a, b = queue[0][0], queue[0][1]
del queue[0]
for each in range(4):
i = a + dx[each]
j = b + dy[each]
if 0 <= i < N and 0 <= j < N and complex_arr[i][j] == "1" :
queue.append([i, j])
complex_arr[i][j] = "0"
count += 1
count_arr.append(count)
for x in range(N):
for y in range(N):
if complex_arr[x][y] == "1" :
BFS(x, y)
count_arr.sort()
print(len(count_arr))
for each in count_arr :
print(each)
```
{문제풀이과정}
- 큐를 좌표로 저장할 것
- count_arr에 집의 개수를 넣어줄 것
=> [BOJ, 2667] 단지번호 붙이기

ssammoo/BOJ/BOJ_7576.py
```python
import sys
from collections import deque
M, N = map(int, input().split())
graph = []
graph.append(list(map(int, sys.stdin.readline().split())))
queue = deque()
dx = [-1, 0, 1, 0]
dy = [0, 1, 0, -1]
for x in range(N):
for y in range(M):
if graph[x][y] == 1:
queue.append([x, y])
def BFS() :
while queue :
x, y = queue.popleft()
for each in range(4) :
i = x + dx[each]
j = y + dy[each]
if 0 <= i < N and 0 <= j < M and graph[i][j] == 0 :
graph[i][j] = graph[x][y] + 1
queue.append([i, j])
BFS()
isTrue = False
result = -2
for x in graph :
for y in x :
if y == 0 :
isTrue = True
result = max(result, y)
if isTrue == True :
print(-1)
elif result == 1 :
print(0)
else :
print(result - 1)
```
{문제풀이과정}
- queue에 좌표를 저장(1)
- 1 주변을 +1 씩 변화시켜감
=> [BOJ, 7576] 토마토

ssammoo/BOJ/BOJ_11053.py
```python
get_arr = list(map(int, input().split()))
dp = [0 for each in range(N)]
for each_inner in range(each) :
if get_arr[each] > get_arr[each_inner] and dp[each] < dp[each_inner] :
dp[each] = dp[each_inner]
dp[each] += 1
print(max(dp))
```
{문제풀이과정}
- https://www.youtube.com/watch?v=sYh62pujaH8&t=60s
=> [BOJ, 11053] 가장 긴 증가하는 부분 수열

ssammoo/BOJ/BOJ_2110.py, ssammoo/PGS/PGS_hash_1.py
```python
def solution(participant, completion):
dict_for_solution = {}
for each in participant :
if each in dict_for_solution :
dict_for_solution[each] += 1
else :
dict_for_solution[each] = 1
for each in completion :
if each in dict_for_solution :
dict_for_solution[each] -= 1
if dict_for_solution[each] == 0 :
del dict_for_solution[each]
return list(dict_for_solution.keys())[0]
```
{문제풀이과정}
- 해시
=> [PGS, hash_1] 완료하지 못한 선수

ssammoo/PGS/PGS_stack_queue_1.py
```python
def solution(progresses, speeds):
queue = progresses
speed_queue = speeds
queue_count = 100
count_list = []
count = 0
while queue_count >= 0 :
if len(queue) == 0 :
count_list.append(count)
break
if queue[0] >= 100 :
queue.pop(0)
speed_queue.pop(0)
count += 1
continue 
if count > 0 :
count_list.append(count)
queue_count -= count
len_num = len(queue)        
for index in range(len_num) :
queue[index] = queue[index] + speed_queue[index]
count = 0
return count_list
```
{문제풀이과정}
=> [PGS, stack_queue_1] 기능개발
